spring:
  application:
    name: isoftstone-security
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_security?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
server:
  port: 8666

mybatis-plus:
  # ?????src/main/java??? classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # ?????resource?? classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mapper/*.xml, classpath:mybatis/mapping/**/*.xml
  #???????package?????????
  typeAliasesPackage: com.example.background.**
  global-config:
    #????  0:"???ID??", 1:"????ID",2:"????ID (??????ID)", 3:"????ID UUID";
    id-type: 0
    #???? 0:"????",1:"? NULL ??"),2:"????"
    field-strategy: 1
    #???????
    db-column-underline: true
    #??mapper ????
    refresh-mapper: true
    #??????????
    #capital-mode: true
    #?????????,?????????????,??????bean??
    #key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #?????????3????
    logic-delete-value: 0
    logic-not-delete-value: 1
    #???sql???,?????????????,??????bean??
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #???????????,?????????????,??????bean??
    # meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    #???SQL???
    #sql-injector: com.baomidou.springboot.xxx
    # SQL ??????????? @SqlParser ????
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false